FROM debian:latest

# Instalar iptables
RUN apt-get update && apt-get install -y iptables

# Copiar el script de configuración del firewall
COPY firewall-config.sh /usr/local/bin/firewall-config.sh

# Dar permisos de ejecución al script
RUN chmod +x /usr/local/bin/firewall-config.sh

# Ejecutar el script cuando el contenedor se inicie
CMD ["/usr/local/bin/firewall-config.sh","python", "app.py"]

