
services:
  persistencia:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: persistencia
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario-12345
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - diplomado-main_network

  web-app:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - diplomado-main_network
    depends_on:
      - persistencia
    environment:
    - FLASK_ENV=development  # Activa el modo de desarrollo (debug)
    command: flask run --host=0.0.0.0 --port=5000 --debug  # Ejecuta Flask con debug activado  

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: persistencia
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - diplomado-main_network
    depends_on:
      - persistencia

  firewall:
    build: ./firewall
    cap_add:
      - NET_ADMIN  # Permitir la administración de la red (iptables)
    networks:
      - diplomado-main_network
    depends_on:
      - web-app
      - persistencia
    command: /usr/local/bin/firewall-config.sh  # Ejecutar el script al iniciar el contenedor

networks:
  diplomado-main_network:
    driver: bridge
