services:
  persistencia:
    image: mariadb
    container_name: persistencia
    environment:
      - MARIADB_ROOT_PASSWORD=persistencia-12345
      - MARIADB_DATABASE=persistencia
      - MARIADB_USER=usuario
      - MARIADB_PASSWORD=usuario-12345
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:z
    ports:
      - "3306:3306"
    networks:
      - webapp-network  

  web-server:
    image: nginx
    container_name: web-server
    volumes:
      - ./app/templates:/usr/share/nginx/html:ro
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-app
    ports:
      - "80:80"
    networks:
      - webapp-network

  web-app:
    build:
      context: ./app  # El directorio donde está tu Flask
    container_name: flask_app
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    networks:
      - webapp-network
    ports:
      - "5000:5000"  # Asegúrate de que este mapeo esté presente

  firewall:
    build:
      context: ./firewall
    container_name: firewall
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      - webapp-network

networks:
  webapp-network:

