version: '3.8'

services:
  persistencia:
    image: mariadb
    container_name: persistencia
    environment:
      - MARIADB_ROOT_PASSWORD=persistencia-12345
      - MARIADB_DATABASE=persistencia
      - MARIADB_USER=usuario
      - MARIADB_PASSWORD=usuario-12345
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:z
    ports:
      - "3306:3306"  # Mapea el puerto de la conexión de la base de datos
    networks:
      - webapp-network  

  web-server:
    image: nginx
    container_name: web-server
    volumes:
      - ./app/templates:/usr/share/nginx/html:ro  # Carpeta donde está index.html
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf  # Configuración de Nginx
    depends_on:
      - web-app
    ports:
      - "80:80"
    networks:
      - webapp-network

  web-app:
    build:
      context: ./app  # El directorio donde está tu Flask
    container_name: flask_app
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    networks:
      - webapp-network

  firewall:
    build:
      context: ./firewall  # El directorio donde está tu Dockerfile del firewall
    container_name: firewall
    cap_add:
      - NET_ADMIN  # Permiso para modificar la red y usar iptables
    privileged: true  # Requiere permisos elevados para modificar iptables
    networks:
      - webapp-network

networks:
  webapp-network:
